# ===============================
# DATABASE CONFIGURATION (H2 FILE MODE - PERSISTENT)
# ===============================

spring.datasource.url=jdbc:h2:file:./emsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# THYMELEAF
# ===============================

spring.thymeleaf.cache=false

# ===============================
# SERVER
# ===============================

server.port=8080